name: Java Square Cafe
address: "103 W. Landry St Opelousas, LA 70570"
email: "info@javasquare.cafe"
phone: (337) 678-1055
include: ['_pages', '_data','login.html','login','_vendors', '_plugins']
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@javasquare.cafe
baseurl:
logo: "/images/logo.png"
favicon: assets/images/favicon.png
locale: en_us
ganalytics: UA-48421544-1
social: "https://twitter.com/javasquare \nhttps://www.facebook.com/javasquare
  \nhttps://www.instagram.com/javasquare"
defaults:
-
  scope:
    path: ""
  values:
    layout: default
    _options:
      content: &content_defaults
        uploads_dir: "uploads/:title"
        format: p h1 h2 h3 h4 h5 h6 div
        styles: /assets/css/theme.css
        undo: true
        redo: true
        left: text-left
        center: text-center
        right: text-right
        justify: justify-content-center
        bold: true
        italic: true
        underline: true
        strike: true
        subscript: false
        superscript: false
        blockquote: true
        table: true
        copyformatting: true
        removeformat: true
        numberedlist: true
        bulletedlist: true
        outdent: false
        indent: false
        image: true
        link: true
        embed: true
-
  scope:
    path: ""
    type: "products"
  values:
    layout: "product"
-
  scope:
    type: pages
    path: _pages/index.html
  values:
    permalink:
-
  scope:
    type: posts
  values:
    layout: bloglayout
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
